name: pluspay_a2a
description: "A new Flutter plugin project."
version: 0.1.0
homepage:

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  android_intent_plus: ^6.0.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5


flutter:
  plugin:
    platforms:
      android:
        package: tr.com.pluspay.pluspay_a2a
        pluginClass: PluspayA2aPlugin

